In [1]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [3]:
#Visualization
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
import os
print(os.path.abspath("house-predict-price.ipynb"))

C:\Users\dell\house-predict-price.ipynb

In [4]:
#Models
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor

In [5]:
#Metrics
from sklearn.metrics import r2_score

In [6]:
df = pd.read_csv(r'C:\data-science-ai\house-predict-model\data\housing_data.csv')

In [7]:
df.head()

,Unnamed: 0,new_price,desc,address,chambres,salles de bains,surface,ascenseur,floor,terrasse,parking,Type,City,Nighberd
0,0,1000000,Appartement traversant de 98 m² au cœur du Bel...,Appartement à vendre Casablanca - Belvédère,2,1,98,Yes,5,Yes,No,Appartement,Casablanca,Belvédère
1,1,1750000,Bureau à vendre de 173 m² à Casablanca – Votre...,Bureau à vendre Casablanca - Autre,1,2,173,Yes,7,Yes,No,Bureau,Casablanca,Autre
2,2,2600000,"Découvrez votre futur chez-vous à Mandarona, C...",Appartement à vendre Casablanca - Californie,3,2,150,Yes,3,Yes,Yes,Appartement,Casablanca,Californie
3,3,2290000,À vendre – Appartement lumineux de 130 m² enti...,Appartement à vendre Casablanca - Les Hôpitaux,2,1,130,Yes,3,No,No,Appartement,Casablanca,Les Hôpitaux
4,4,1460000,Bienvenue dans ce charmant appartement situé d...,Appartement à vendre Meknès - Hamria,3,2,163,Yes,2,No,No,Appartement,Meknès,Hamria

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4675 entries, 0 to 4674
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       4675 non-null   int64
 1   new_price        4675 non-null   int64
 2   desc             4675 non-null   str
 3   address          4675 non-null   str
 4   chambres         4675 non-null   int64
 5   salles de bains  4675 non-null   int64
 6   surface          4675 non-null   int64
 7   ascenseur        4675 non-null   str
 8   floor            4675 non-null   int64
 9   terrasse         4675 non-null   str
 10  parking          4675 non-null   str
 11  Type             4675 non-null   str
 12  City             4675 non-null   str
 13  Nighberd         4675 non-null   str
dtypes: int64(6), str(8)
memory usage: 511.5 KB

In [14]:
df = df.drop("Unnamed: 0", axis=1)

In [15]:
df.describe()

          new_price    chambres  salles de bains      surface        floor
count  4.675000e+03  4675.00000      4675.000000  4675.000000  4675.000000
mean   1.871291e+06     2.32000         1.680000   143.720000     3.200000
std    1.348472e+06     1.91269         0.835314   158.579131     1.385789
min    6.770260e+05     1.00000         1.000000    32.000000     1.000000
25%    1.000000e+06     1.00000         1.000000    50.000000     3.000000
50%    1.460000e+06     2.00000         1.000000    83.000000     3.000000
75%    1.794000e+06     3.00000         2.000000   150.000000     4.000000
max    6.800000e+06    10.00000         4.000000   720.000000     7.000000